{
    "openapi": "3.0.1",
    "info": {
        "title": "Carts",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "When a customer adds a set of products to their cart and makes a purchase, store that purchase as an individual order. You can then update that order with tracking information once the shipping label has been printed.",
        "x-hubspot-related-documentation": [
            {
                "name": "Carts overview",
                "url": "https://developers.hubspot.com/beta-docs/guides/api/crm/commerce/carts"
            }
        ],
        "x-hubspot-introduction": "Use the orders API to create and manage data related to ecommerce purchases in HubSpot. This can be especially useful for keeping HubSpot data synced with external ecommerce platforms, such as Shopify and NetSuite."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/objects"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/carts/batch/read": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Read a batch of carts by internal ID, or unique property values",
                "operationId": "post-/crm/v3/objects/carts/batch/read",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    }
                ]
            }
        },
        "/carts/{cartId}": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a cart by ID",
                "description": "Read an Object identified by `{cartId}`. `{cartId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/carts/{cartId}",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Basic"
                ],
                "summary": "Archive a cart by ID",
                "description": "Move an Object identified by `{cartId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/carts/{cartId}",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    }
                ]
            },
            "patch": {
                "tags": [
                    "Basic"
                ],
                "summary": "Update a cart by ID",
                "description": "Perform a partial update of an Object identified by `{cartId}`. `{cartId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/carts/{cartId}",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    }
                ]
            }
        },
        "/carts/batch/archive": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Archive a batch of carts by ID",
                "operationId": "post-/crm/v3/objects/carts/batch/archive",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    }
                ]
            }
        },
        "/carts/batch/create": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Create a batch of carts",
                "operationId": "post-/crm/v3/objects/carts/batch/create",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    }
                ]
            }
        },
        "/carts/batch/update": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Update a batch of carts",
                "operationId": "post-/crm/v3/objects/carts/batch/update",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    }
                ]
            }
        },
        "/carts": {
            "get": {
                "tags": [
                    "Basic"
                ],
                "summary": "Retrieve a page of carts",
                "description": "Read a page of carts. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/carts",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Basic"
                ],
                "summary": "Create a new cart",
                "description": "Create a cart with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard carts is provided.",
                "operationId": "post-/crm/v3/objects/carts",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    }
                ]
            }
        },
        "/carts/batch/upsert": {
            "post": {
                "tags": [
                    "Batch"
                ],
                "summary": "Batch upsert carts by property",
                "operationId": "post-/crm/v3/objects/carts/batch/upsert",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.write"
                        ]
                    }
                ]
            }
        },
        "/carts/search": {
            "post": {
                "tags": [
                    "Search"
                ],
                "operationId": "post-/crm/v3/objects/carts/search",
                "security": [
                    {
                        "oauth2": [
                            "crm.objects.carts.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.objects.carts.read"
                        ]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": [
                    "ten-secondly"
                ],
                "summary": "Search carts"
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.companies.write": " ",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.deals.write": " ",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.deals.read": " ",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.companies.read": " ",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.quotes.write": "Quotes"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header",
                "x-ballerina-name": "privateAppLegacy"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    }
}